// Generated by Wrangler on Mon May 06 2024 22:01:30 GMT+1000 (Australian Eastern Standard Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
  COMPANY_NAME: 'Next.js';
  TWITTER_CREATOR: '@nextjs';
  TWITTER_SITE: 'https://nextjs.org/commerce';
  SITE_NAME: 'Acme Store';
  SHOPIFY_REVALIDATION_SECRET: '';
  SHOPIFY_STORE_DOMAIN: 'https://graphql.myshopify.com';
  SHOPIFY_STOREFRONT_ACCESS_TOKEN: string;
}
