// Generated by Wrangler by running `wrangler types`

interface Env {
	CACHE: KVNamespace;
	COMPANY_NAME: "Next.js";
	TWITTER_CREATOR: "@nextjs";
	TWITTER_SITE: "https://nextjs.org/commerce";
	SITE_NAME: "Acme Store";
	SHOPIFY_REVALIDATION_SECRET: "";
	SHOPIFY_STORE_DOMAIN: "https://graphql.myshopify.com";
	SHOPIFY_STOREFRONT_ACCESS_TOKEN: string;
	ASSETS: Fetcher;
}
